version: '3'
services:
  db:
    image: mysql:5.7.30
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 0.0.0.0:80:3000
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
